{
  'printWidth': 100,
  'tabWidth': 2,
  'useTabs': false,
  'semi': true,
  'singleQuote': true,
  'jsxSingleQuote': true,
  'trailingComma': 'all',
  'bracketSpacing': true,
  'bracketSameLine': false,
  'jsxBracketSameLine': false,
  'arrowParens': 'always',
  'proseWrap': 'always',
  'importOrder':
    [
      '<THIRD_PARTY_MODULES>',
      '^redux/(.*)$',
      '^service/(.*)$',
      '^hooks/(.*)$',
      '^helpers/(.*)$',
      '^assets/(.*)$',
      '^pages/(.*)$',
      '^components/(.*)$',
      '^interfaces$',
      '^types$',
      '^data/(.*)$',
      '^./(.*)$',
    ],
  'importOrderSeparation': true,
  'importOrderSortSpecifiers': true,
}
